test fail on pr

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -39,6 +39,12 @@ jobs:
             echo "EXISTS=false" >> $GITHUB_ENV
           fi
 
+      - name: Fail PR if tag already exists
+        if: github.event_name == 'pull_request' && env.EXISTS == 'true'
+        run: |
+          echo "Error: Version v${{ env.VERSION }} already exists!"
+          exit 1
+
       - name: Create and push tag
         if: github.event_name == 'push' && env.EXISTS == 'false'
         run: |
